[package]
name = "plasmid_tools"
version = "0.6.9"
edition = "2021"
authors = ["David O'Connor <the_alchemist@fastmail.com>"]
description = "Tools for primer design, PCR, and other plasmid-related work."
keywords = ["plasmid", "primer", "biology", "pcr"]
categories = [
    "science", "science::bioinformatics",
]
repository = "https://github.com/David-OConnor/plasmid_tools"
documentation = "https://docs.rs/plasmid_tools"
readme = "README.md"
license = "MIT"
exclude = [".gitignore"]

[dependencies]
reqwest = { version = "^0.12.5", features = ["blocking", "json"], default-features = false }

eframe = "^0.28.1"
egui_extras = "^0.28.1"  # For tables.
egui_file = "^0.18.0" # For file dialogs.

bio = "^2.0.0"

#chrono = "^0.4.38"
#regex = "1.10.5"

# We use bincode for saving and loading to files.
bincode = "^2.0.0-rc.3"
