[package]
name = "plasmid_check"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "^0.12.5", features = ["blocking", "json"], default-features = false }

eframe = { version = "0.28.1"}
egui_file = { version = "0.18.0" } # For file dialogs.
image = { version = "0.25.1" } # For loading the window icon.

bio = "^2.0.0"
chrono = "0.4.38"
regex = "1.10.5"
serde = { version = "1.0.204", features = ["derive"] }